(package "kibela"
         "0.1.0"
         "Kibela client")

(website-url "https://github.com/mugijiru/emacs-kibela")
(keywords "kibela" "tools")

(package-file "kibela.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "graphql" "0.1.1")
(depends-on "request" "0.3.3")
(depends-on "markdown-mode" "2.5")
(development
 (depends-on "noflet")
 (depends-on "with-simulated-input"))
