[[https://img.shields.io/github/v/tag/mugijiru/emacs-kibela.svg]]

* kibela.el

** 注意
   このパッケージは開発途中のため突然仕様が変わることがあります。

** これは何?

   Emacs から [[https://kibe.la][Kibela]] を操作するためのパッケージです。

** できること

   現時点では

   - デフォルトグループの記事一覧の表示
   - デフォルトグループへの記事の作成
   - テンプレートを用いた記事の作成
   - 既存の記事の閲覧
   - 既存の記事の更新
   - チームの切り替え

   ができます。

** 設定
*** 認証情報
    kibela.el を利用するためにはカスタマイズ変数 ~kibela-auth-list~ 認証情報を設定する必要があります。
    1認証毎に ~(NAME TEAM ACCESS_TOKEN)~ の組み合わせの項目を ~kibela-auth-list~ に追加してください。

    認証情報は複数登録でき、それらを切り替えて利用することができます。

**** 設定例
     #+begin_src emacs-lisp
       (custom-set-variables
       '(kibela-auth-list `(("Work" "biz-team-name1" "secret/dummy-access-token")
                            ("Private" "my-private-team" "secret/dummy-access-token-for-my-team"))))

     #+end_src

*** 1回毎の取得件数
    グループの記事一覧を取得する際の1ページ毎の件数の設定は ~kibela-per-page~ で設定可能です。

    大きな値を設定した場合には1リクエストで実行可能な実行コストを越えてしまったり、
    越えていなくても処理し切れずにエラーとなる場合があるので
    50以下の値を推奨します。

    デフォルト値は 40 です。

** 操作
*** デフォルトグループの記事一覧の表示
    #+begin_example
    M-x kibela-group-notes
    #+end_example

    を実行するとデフォルトグループの記事を取得できます。

    ただし現時点の実装では、
    デフォルトグループの情報が取得できてない時には
    "デフォルトグループの取得ができていません" というメッセージが表示されて処理が止まります。

    最初の一発目の取得の際は必ずそういう挙動になるため、
    その場合はもう一度同じコマンドを実行してください。

    記事一覧画面では、以下のキーバインドを利用できます。

    - ~RET~ :: 記事の閲覧
    - ~>~ :: 次のページを表示
    - ~<~ :: 前のページを表示
    - ~q~ :: 終了

    記事一覧バッファは ~tabulated-view-mode~ をベースにしているので、
    その他のキーバインドについてはそちらの ~keymap~ をご参照ください。

*** 記事の閲覧
    記事一覧ページでは記事名の上で Enter をタイプすると記事を表示することができます。

    記事閲覧バッファでは以下のキーバインドが使えます。

    - ~C-c C-e~ :: 記事編集
    - ~C-c C-c C-o~ :: ブラウザで記事を開く
    - ~C-c C-z~ :: 終了

    記事閲覧バッファは ~gfm-view-mode~ をベースにしているので、
    その他のキーバインドについてはそちらの ~keymap~ をご参照ください。

*** 記事の編集
    記事編集バッファでは Markdown で記事を編集することができます。
    また、以下のキーバインドを利用できます。

    - ~C-c C-c C-c~ :: 記事の投稿
    - ~C-c C-c C-o~ :: ブラウザで記事を開く
    - ~C-c C-z~ :: 終了

    記事編集バッファは ~gfm-mode~ をベースにしているので、
    その他のキーバインドについてはそちらの ~keymap~ をご参照ください。

**** 注意
     グループやフォルダの変更機能は未実装です。
*** 記事の作成
    #+begin_example
    M-x kibela-note-new
    #+end_example

    を実行すると、まず作成する記事タイトルが聞かれます。
    そちらを入力すると、新しい記事を書くためのバッファが表示されます。

    記事の新規作成バッファでは記事編集バッファと同様に、以下のキーバインドを利用できます。

    - ~C-c C-c C-c~ :: 記事の投稿
    - ~C-c C-c C-o~ :: ブラウザで記事を開く
    - ~C-c C-z~ :: 終了


    記事の新規作成バッファは記事編集バッファと同様に ~gfm-mode~ をベースにしているので、
    その他のキーバインドについてはそちらの ~keymap~ をご参照ください。
**** 注意
     グループやフォルダの変更機能は未実装であるため、投稿先はデフォルトグループのみとなっています。

*** テンプレートを用いた記事の作成
    #+begin_example
    M-x kibela-note-new-from-template
    #+end_example

    を実行すると、記事テンプレートを選択して記事を書くことができます。
    記事テンプレートを選択後には記事の新規作成バッファが表示されます。

    その他の操作は記事の新規作成と同様です。

**** 注意
     グループやフォルダの変更機能は未実装であるため、
     投稿先はテンプレートで設定されているデフォルトグループのみとなっています。

*** チームの切り替え
    #+begin_example
    M-x kibela-switch-team
    #+end_example

    を実行すると、チーム選択を促すプロンプトが表示されます。
    ~kibela-auth-list~ に設定した認証情報が選択できます。
