name: create-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag(ex: v1.2.3)"
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Generate release note contents
        id: release_note
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const result = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ inputs.tag }}',
            })
            console.log(result.data.body)
            return result.data.body

      - name: Create release
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const result = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ inputs.tag }}',
              name: '${{ inputs.tag }}',
              body: ${{ steps.release_note.outputs.result }},
              draft: false,
              prerelease: true,
            })
            console.log(result.data)
            return result.data
