name: tagging

on:
  pull_request:
    branches:
      - 'main'
    types: [closed]
  workflow_dispatch:

jobs:
  test:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bump-version')

    uses: ./.github/workflows/test.yml
    secrets: inherit

  # copy from bump-version.yml
  # FIXME: reusing workflow か action として定義し直して再利用する
  detect-current-version:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'bump-version')

    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.detect-current-version.outputs.version }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: detect current version
      id: detect-current-version
      env:
        VERSION_LINE_PREFIX: ";; Version: "
      run: |
        version=$(grep "^${VERSION_LINE_PREFIX}" kibela.el | sed -e "s/^${VERSION_LINE_PREFIX}//")
        echo $version
        echo "version=${version}">> $GITHUB_OUTPUT

  tag:
    runs-on: ubuntu-latest
    needs:
      - test
      - detect-current-version

    permissions:
      contents: write
      packages: write

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # 要らないかも?
      - name: get latest tag
        id: latest-tag
        uses: actions/github-script@v7
        with:
          script: |
            const result = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            return result.data.tag_name

      - name: debug
        run: |
          echo "latest_tag=${{ steps.latest-tag.outputs.result }}"
          echo "version=${{ needs.detect-current-version.outputs.version }}"

      - name: set tag
        id: tag
        run: |
          git tag v${{ needs.detect-current-version.outputs.version }}
          git push origin --tags
          echo "tag=v${{ needs.detect-current-version.outputs.version }}" >> $GITHUB_OUTPUT

  call-create-release:
    needs: tag
    secrets: inherit
    uses: ./.github/workflows/create-release.yml
    with:
      tag: ${{ needs.tag.outputs.version }}
    permissions:
      contents: write
      packages: write
