name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'Eask'
      - '*.el'
      - 'test/*-test.el'
      - '.github/workflows/test.yml'
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 27.2
          - 28.2
          - snapshot

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run tests
      run: |
        eask clean all
        eask install-deps --dev
        eask package
        eask install --dev
        eask compile
        eask test ert-runner

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.2

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Setup Code Climate test-reporter
      run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter

    - name: CodeClimate prebuild
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
      run: ./cc-test-reporter before-build

    - name: Setup test report location
      run: mkdir -p coverage

    - name: Run tests
      env:
        UNDERCOVER_FORCE: true
      run: |
        eask clean all
        eask install-deps --dev
        eask test ert-runner

    - name: CodeClimate afterbuild
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
      run: ./cc-test-reporter after-build -t simplecov -d

  lint-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.2

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run lint
      run: |
        eask clean all
        eask lint package

  lint-indent:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.2

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run lint
      run: |
        eask clean all
        eask lint indent

  lint-elint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: 28.2

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - name: Run lint
      run: |
        eask clean all
        eask install-deps --dev
        eask lint elint
